name: Build Documentation
on:
  workflow_dispatch:
    inputs:
      add_version:
        description: "The version to add"
        required: false
      remove_version:
        description: "The version to remove"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env variable
        run: echo "VERSION=${{ github.event.inputs.add_version }}" >> $GITHUB_ENV

      - run: npm install

      # This is used when you were to remove old version and add a new version into lib
      - name: Remove existing docs
        if: ${{ github.event.inputs.remove_version != '' }}
        run: rm -r -v ./lib/${{ github.event.inputs.remove_version }}

      - name: Build source files
        run: tsc --build

      - name: Generate static pages
        run: npm run start

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: ./docs/.vuepress/dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Upload Docs
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: ./lib
          message: "Uploaded Script API Docs - ${{ github.event.inputs.add_version }}"
