name: Build Documentation
on:
  schedule: 
    - cron: "00 17 * * 2-4"
  workflow_dispatch:
    inputs:
      remove_version:
        description: "The version to remove"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: npm install

      # This is used when you were to remove old version and add a new version into lib
      - name: Remove existing docs
        if: ${{ github.event.inputs.remove_version != '' }}
        run: |
          IFS=',' read -ra VERSIONS <<< "${{ github.event.inputs.remove_version }}"
          for version in "${VERSIONS[@]}"; do
            rm -r -v "./lib/${version}"
          done
    
      - name: Build source files
        run: tsc --build

      - name: Generate static pages
        run: npm run start
        env:
          ADSENSE_CLIENT: ${{ secrets.ADSENSE_CLIENT }}
          MEASURE_ID: ${{ secrets.MEASURE_ID }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: ./docs/.vuepress/dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Upload Docs
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: ./lib
          message: "Uploaded Script API Docs"
